import type { Product, Project, NewsArticle, TeamMember } from "@/types";

export const FEATURED_PRODUCTS: Product[] = [
  {
    _id: "1",
    name: "Premium Baltic Birch",
    series: "Architect-Spec",
    slug: "premium-baltic-birch",
    description:
      "Grade A/A birch plywood for high-end architectural applications.",
    grade: "Grade A/A",
    category: "Birch Premium",
    thickness: [12, 18, 24],
    material: "Baltic Birch",
    bonding: "WBP Phenolic",
    dimensions: ["1220×2440mm", "1525×3050mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBS_-cCku_CTugd29Q4FXxJrE57ECOuRBDLSjrygWILiJB85-T88MDbUPrdnldSkFxaAEIBzOl0kKUr4qKJ16CWjTDHzCjAd0nAgi-SCK_YT3WJ1kbYmMgvQn7m5yj1dhmZXa8xoEoAQC1UhGY2FPqFqJQmDh5RAvf9CqjsZE6lX-qV7APdZRWIlN-pRpZNck1jIwUXiXN9YFHtABz7b9GmddyoHN5yA3IDHDdGsAQcHyZWS177ESPWCkeKbIvcELF_i_zWxq2JFvMi",
    galleryImages: [],
    certifications: ["FSC", "PEFC"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "2",
    name: "Okoume Marine Grade",
    series: "Marine-Pro",
    slug: "okoume-marine-grade",
    description: "BS 1088 certified marine plywood for demanding environments.",
    grade: "BS 1088",
    category: "Film Faced",
    thickness: [9, 12, 15, 18],
    material: "Okoume",
    bonding: "WBP Marine Glue",
    dimensions: ["1220×2440mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDM7i8QoD7tKWOrufhBjrVQqaYwGcA5IypeE3-mdzqPlMbsL80brsMPFSJL8VV6qD3MYk7FI563i7MseubLk9udY3x0Jn1xnWfIsFzA2mJy0ECkc-7aRbY1KJAufUcQ-QyCkqt_Mn-d-5Mvl7PkUraH2UHInU_IHsKmZFkLhmyM7-r297RLWITKNKM4qk4k1UiZC9b-VohVRmFz1d8cNfjK81DxGECgHB9sV2KBO2sZmDySHSBCQTVqqfICw9wiw94mZ9GzYEWLjxWQ",
    galleryImages: [],
    certifications: ["BS 1088", "FSC"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "3",
    name: "Film-Faced Concrete",
    series: "FormWork-X",
    slug: "film-faced-concrete",
    description:
      "High-strength film-faced plywood for concrete formwork applications.",
    grade: "Grade A+",
    category: "Film Faced",
    thickness: [18, 21],
    material: "Birch Core",
    bonding: "Phenolic Film",
    dimensions: ["1220×2440mm", "1250×2500mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCl7YZ8FYIXQg-oN-R0I-1ENMUHwtGA8YAqHpsln4NwoDjwCIC8JWL_kcJpoq9SmdsICBKo0L-mvWqxlG65zcY4LDFJm6al4d_f_4G28VVHwgcp_ksOhLicuTIfPquq-oKjgxUAt4NARZtFHJgnxbnfz6Uw8Yu0l63NE6aXe9D7YiNbIu7Ezwm32ZwnSNZrTlURit_Kx6FnPlzBYjC-XXit24ibK5oJoB1GydGDqmh-BAPNSFylRSTF1ERnncMmoGvEyVsNX4RSm9Zx",
    galleryImages: [],
    certifications: ["ISO-14001", "FSC"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  {
    _id: "4",
    name: "Arctic Birch Core",
    series: "Arctic-Series",
    slug: "arctic-birch-core",
    description: "Premium birch core plywood for furniture and cabinetry.",
    grade: "Premium Birch",
    category: "Birch Premium",
    thickness: [24],
    material: "Arctic Birch",
    bonding: "MR Glue",
    dimensions: ["1525×3050mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAscm9XraAQLEfVa9VUAwtvNpFYsVlf89oG1XphH-iUV_wZw_RRlPIbZ5WjU46dIa3jUiWmQwaCcm9D4P39BJBM6H5bp5xH_feUsw10q0PZz47fJV8FcER-bUbYReMWM-OQ2bhsah3S1rMmo5Bu9VdDELM0Ju1SApX0KbYSFKddoKCYD7usUvooAtGS-B5zR7u-5RCuhESNv0AIegKCDJNv8j-wJiC4GwzmxUAffR8S_F6ZWVIfIOz8vYL2ftchLCSmXhzCKYJbswuT",
    galleryImages: [],
    certifications: ["FSC"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "5",
    name: "Commercial Oak Veneer",
    series: "Oak-Series",
    slug: "commercial-oak-veneer",
    description: "Export grade oak veneer plywood for commercial applications.",
    grade: "Export Grade",
    category: "Commercial",
    thickness: [12],
    material: "Oak Veneer",
    bonding: "MR Glue",
    dimensions: ["1220×2440mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAAa1Sl6Jkqh3jvel4xhyGVhtdr5RTriPfPnjEoRnVyhJlf6akMlatSzjVmnjWpcXSTK2hqQ3I1uVmmoOMjgyy8N66Jc68DN_t1K7xAkTg52OzHs5PSfyWtxc5fqoVnnnp4STGZAdXcTfDL2iha_GDq4ayJ4I0OA950voyzotUIhrz8Bveo4Ut_vIVkIAodNFvqZCPfW4seMpkX5QcO7SfaFr86Gl589athJdpknCKvfK_x5ST1mzVbTRPERiMV79-Jfs7G0qVWrhZU",
    galleryImages: [],
    certifications: ["PEFC"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    _id: "6",
    name: "H-Form Concrete Panels",
    series: "FormWork-H",
    slug: "h-form-concrete-panels",
    description:
      "Heavy-duty formwork panels for high-pressure concrete casting.",
    grade: "Formwork",
    category: "Film Faced",
    thickness: [21],
    material: "Hardwood Core",
    bonding: "Phenolic Film",
    dimensions: ["1220×2440mm"],
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBWiHOBLmTASfz1I_dkMNi6tnfRoErm6VaIkMeqJ9D0ynu89oIhDbew5OMtkPRek5dL8lWdw9P3szRFhOGzIGlORojTu3IxNDcDhpECguEA_Xfwgzt-Hh7wony4dEGANpYFYYIsbFWS5dDzcRiDckkE0dDi6dmvbsVcC1Zc1dA2rwa9_adQJ-pTjkRiCTej1B8evjNzwMT_T2PTCLpr_9wnG8829d1bH-WJQbxu1y-Ec-FV2EAEBdeVnm27PGgcQs33Efl6netCWtVW",
    galleryImages: [],
    certifications: ["ISO-14001"],
    availability: "In Stock",
    specifications: [],
    applications: [],
    featured: false,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const PROJECTS: Project[] = [
  {
    _id: "1",
    title: "The National Theatre Hub",
    description: "Architectural acoustic paneling system",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCa-XGKrwtgZlDj2laoH2DsjfoXq3XNqZTLcGBvALocxLxmoNmBwz4ee3XkYOq8Wy854wWOdMjsm8TJvZhHNpUp4SoRznwV5kQwV6SAfUytP53EOZjJANxvnFv7jCpDwH6BYgowKgfbKABPgb6MIBoBr2imrvIydPVVfS_gF3ZRITc7-hXjyGg5EXiuDSRadtN_GSeUI87uVCdivb6XfSz2mpGFjxHNSd0BPZ8LWxznjEFJ6h_cYAMxk_BN1Jl6imbuqLoNkyTettEJ",
    category: "Commercial",
    location: "London, UK",
    year: 2023,
    featured: true,
    createdAt: "2024-01-01",
  },
  {
    _id: "2",
    title: "Linear Office Concept",
    description: "Minimalist workspace with bespoke plywood desks",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBX_A_FkU1yiAYYPdpxLINnFEPmPwNi63SHjtJg3ss6P3RpsS4IgfCcWyuZu7P3lsu9sfZGNp0xZeIQIAzf_F_1iPbXVTG6tHqpfYVm9paP35hrG3YBr3O-uWV9sY2auEw52DRqldixhIPkhlD5uY0vkt4t5zDJEW9lZDvKpdq5X2L0hQShx6OtxuDAchV85xB-idssSkbj-HLkZEkyqN16uVhzLWgBMRLS-coI4LMQ_5yL9dztIGFhHdAFen5kgMmnqaF0rHlnEG8n",
    category: "Commercial",
    location: "Singapore",
    year: 2023,
    featured: true,
    createdAt: "2024-01-01",
  },
  {
    _id: "3",
    title: "Bespoke Residential Loft",
    description: "Luxury kitchen island in walnut plywood",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDI2hGXUi0ar6R1YdGBVByYkkyEg61Zf7PtN7NAySiLt5CeVYiXqCqkQLm3ehNaLJWbub4zlD5Xy9mgB7KKhjxGIZnlf0dLGxOhERXH3b7jFMqXY8BGuZ0uUWez76H9NvBK2bWbZQVGLEl1OqUUn_zLs5HP-gBqhnnZkDcWQtXE4eOEp05JUav0COCt3gYBqTmeemmDM9FL6AY3tpRR2mWdTOtq2uHs8Lpu7ezv-1sCH0I2xb5hXJA6L8tIxSBZuPAdOcoFNV3gJ6Cr",
    category: "Residential",
    location: "Amsterdam, NL",
    year: 2024,
    featured: true,
    createdAt: "2024-01-01",
  },
];

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    _id: "1",
    title: "The Shift to Mass Timber in European Export Markets",
    content: "",
    excerpt:
      "How cross-laminated timber and engineered wood products are reshaping export dynamics across the European construction sector.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBUDYgbU7TCCCFJehhLd9OR-JeuFU3Qy4UX9HrCLfJ3Om3Qu3dy4FKxD12oliP82Y-2Pp-0JfoldrkfKKjHzvIIi3lhpMALPlHkNkfc9UYolceIso2DdC6a63d62e3pwqWLWbX2D4L6Gsmi46JL7u3GAET2y-3BPXtST3PyJ-Yrg_6Ee4FgoBQmKFw8dR_oG_OmVZD0IqLd_Lr81s2rI_LdfBNkxgUDkAzoucQ_Zcb5eqd1T1I3fFIW_GYVTcz07qw3Sg-Kd_ewyQ_O",
    author: "Editorial",
    publishDate: "2024-03-12",
    slug: "shift-mass-timber-european-export",
    tags: ["timber", "export", "europe"],
    createdAt: "2024-03-12",
  },
  {
    _id: "2",
    title: "Advancements in Phenolic Resin Technology",
    content: "",
    excerpt:
      "New formulations in phenolic bonding agents are extending the lifecycle of film-faced plywood in extreme environments.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDeA6vuIfSZh8XEl4eRZkhqoa5fCGDhJEiV_PJJBVTRKZCRwnulEtuun89xHeFFXWC2PV5xg8oqPHHSTI1v1SCn-q3zR7S4y8PGZG0bPmpdRrHVP4tGZrCYAwEFP1NE1YBeLZJ88KQ7yvfcC2qP6V_hAG3pY73frCJbCmnFAbQfm8H1TEesxsW7QM8zUNOurovBMNXNkbFXcJ75lpVEqoPLKn_ePB_DCSWiOoMRtgAGCAdcWN6h5fVg34bA46C2If8ucNa6NKvRHF-M",
    author: "Editorial",
    publishDate: "2024-02-28",
    slug: "phenolic-resin-advancements",
    tags: ["technology", "phenolic", "innovation"],
    createdAt: "2024-02-28",
  },
  {
    _id: "3",
    title: "Woodland's Net-Zero Roadmap: 2030 Forestry Goals",
    content: "",
    excerpt:
      "Our commitment to carbon-neutral manufacturing and responsible forestry practices ahead of our 2030 sustainability targets.",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDrePdByVR1rY-wxi1XXaLVYeWphWFqoxJIUugWshNOcD741FXxs_Tz_-FVRB3QxXWgmblRYIIct8Vi0p-hmC6liQcEkMhkZ3k-iRbl_D9btYfdiFPlvIqOfHr9KjMnwsnyP9QRkN-SGZb6-94cXMEhYbXmK2oXetSSigCKhC9yCoSRrCWTacjx6MsDl9dI8YCMGJHPoki02GhmhNEVMitnmRraY9kY4Qgzb0ZqtL2UTWw7eRxYvwUr1QkW_1rTYhvBZmkpfnoK1J2a",
    author: "Editorial",
    publishDate: "2024-01-15",
    slug: "net-zero-roadmap-2030",
    tags: ["sustainability", "net-zero", "forestry"],
    createdAt: "2024-01-15",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    _id: "1",
    name: "Marcus Thorne",
    title: "Global Sales Director",
    region: "Executive Leadership",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCjD-WIPgnZRNIi2p9s13nBKm5qZ_wxylupiVipC5QW5qF6EuzsYMEpNjVk1e_fUstf73KnSXjALgX1DRaqeJwl6NvIctiFdKm2QR4Lglijk0PS1L0QN45duQfuHBkhLVsCC2dKRuQH6MklGzOUVjkU-oQ8CuVvy2AOrhy03GVS-ErLk8YmCPhFmqSfkJhngsimtiaMFsSuYmC4SDdESsLAakwZpBpJGgtm1pz5JPP4-iSnPD2NkRBzFnnimzZ_R9RFcmoGAHsE06To",
    email: "m.thorne@woodland.com",
    phone: "+44 20 7946 0123",
    whatsapp: "+447946012300",
    zalo: "",
    order: 1,
  },
  {
    _id: "2",
    name: "Elena Vance",
    title: "Strategic Accounts Manager",
    region: "Asia-Pacific",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCY6FCSoN-fOwaJNdNZOdFWMJF7vTLMQJmDQnP7QQNaGGRlXwMqTRHq7twmWAYyBTUjH762R0KfVB4LxZqgATXUAu24KK4XGPdUcMNx7lysz8qZ7dmWvA_iazty0gLpEjReK-pqAIBIStKuljbKne-jtIaAL4jrv_PWzlvEE6wh3z4TSj8HWUg-B0AQJs4qXIpJqNDO6VQNX3ASLe0QhwoXTWnXwBSvBTNJb8GX6ny_VdMia6fsjJP1vwybuXF5xVKdzYoto9MdmRxp",
    email: "e.vance@woodland.com",
    phone: "+65 6734 1234",
    whatsapp: "+6567341234",
    zalo: "+6567341234",
    order: 2,
  },
  {
    _id: "3",
    name: "Julian Rossi",
    title: "Architectural Consultant",
    region: "EMEA",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAuakD7-sI_yOEv6_YE2r4X6BEtdeSmq3CMtDduqWGr3Kk2uYGAq5yJIJFHNmlciGEIH2DHZSTkx0J01I7tsq_g9RNIH67sn5abXiYjQUYdqEthhM14EDl1gctaNzhBm6u4hljai0rOK6YoydnjMcvnmu6Q8wrOnhdufw3lFMCBCx3w-dYbCVPvgDtFv3fBxPlZBJQ05xbgoT-Qo_v08E3TZA7OaCHPW_l1qaguVMeu_7xtnfylYRqHsHVVYhb82r4reBuZCbj9NFdX",
    email: "j.rossi@woodland.com",
    phone: "+49 30 231 2456",
    whatsapp: "+4930231245600",
    zalo: "",
    order: 3,
  },
];
