import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./messages/**/*.{json}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#331917",
        "surface-bright": "#fbf9f8",
        "on-primary-fixed-variant": "#5e3f3b",
        "primary-container": "#4b2e2b",
        "inverse-on-surface": "#f3f0f0",
        tertiary: "#22211b",
        outline: "#827472",
        "surface-container-high": "#eae8e7",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1c",
        "secondary-container": "#b9ead9",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-container-highest": "#e4e2e1",
        "on-tertiary-fixed": "#1d1c16",
        "tertiary-fixed": "#e7e2d8",
        "on-secondary-fixed": "#002019",
        "on-background": "#1b1c1c",
        background: "#fbf9f8",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#504443",
        "tertiary-container": "#38362f",
        "surface-container-low": "#f5f3f2",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e1",
        "inverse-surface": "#303030",
        secondary: "#396759",
        "on-primary": "#ffffff",
        "on-primary-container": "#be9590",
        "outline-variant": "#d4c3c0",
        "on-primary-fixed": "#2d1512",
        "on-tertiary-fixed-variant": "#494740",
        "surface-container": "#f0eded",
        "primary-fixed": "#ffdad6",
        "secondary-fixed": "#bceddc",
        "primary-fixed-dim": "#e8bcb7",
        "secondary-fixed-dim": "#a0d1c0",
        "on-secondary-container": "#3d6b5e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#204f42",
        surface: "#fbf9f8",
        "inverse-primary": "#e8bcb7",
        "on-tertiary-container": "#a29e96",
        "surface-tint": "#785652",
        "tertiary-fixed-dim": "#cac6bd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};

export default config;
