import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./messages/**/*.{json}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#1f6f3a",
        "surface-bright": "#f7fbf8",
        "on-primary-fixed-variant": "#2f5f45",
        "primary-container": "#2e5e43",
        "inverse-on-surface": "#edf2ed",
        tertiary: "#205739",
        outline: "#6f7f75",
        "surface-container-high": "#e7eeea",
        "on-error": "#ffffff",
        "on-surface": "#171d19",
        "secondary-container": "#c5ebd5",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-container-highest": "#e1e9e4",
        "on-tertiary-fixed": "#0f2719",
        "tertiary-fixed": "#d0efdb",
        "on-secondary-fixed": "#0e281a",
        "on-background": "#171d19",
        background: "#f7fbf8",
        "on-error-container": "#93000a",
        "surface-dim": "#d6dfd9",
        "on-surface-variant": "#415148",
        "tertiary-container": "#2a6141",
        "surface-container-low": "#f1f6f2",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#dde5df",
        "inverse-surface": "#2d3430",
        secondary: "#2f7a53",
        "on-primary": "#ffffff",
        "on-primary-container": "#d9efdf",
        "outline-variant": "#c0d0c6",
        "on-primary-fixed": "#113823",
        "on-tertiary-fixed-variant": "#2f5943",
        "surface-container": "#ebf2ed",
        "primary-fixed": "#b7e4c8",
        "secondary-fixed": "#b8e9cb",
        "primary-fixed-dim": "#8ec9a7",
        "secondary-fixed-dim": "#8fd0b0",
        "on-secondary-container": "#1c5d3d",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#245f40",
        surface: "#f7fbf8",
        "inverse-primary": "#98d3b2",
        "on-tertiary-container": "#d7ecdf",
        "surface-tint": "#2f7a53",
        "tertiary-fixed-dim": "#9ed0b2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};

export default config;
